package pe.com.soappet.dominio;
// Generated 11/06/2015 06:29:28 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Cita generated by hbm2java
 */
public class Cita  implements java.io.Serializable {


     private int idCita;
     private Integer idmascota;
     private Integer iddoctor;
     private Date fechaCita;

    public Cita() {
    }

	
    public Cita(int idCita) {
        this.idCita = idCita;
    }
    public Cita(int idCita, Integer idmascota, Integer iddoctor, Date fechaCita) {
       this.idCita = idCita;
       this.idmascota = idmascota;
       this.iddoctor = iddoctor;
       this.fechaCita = fechaCita;
    }
   
    public int getIdCita() {
        return this.idCita;
    }
    
    public void setIdCita(int idCita) {
        this.idCita = idCita;
    }
    public Integer getIdmascota() {
        return this.idmascota;
    }
    
    public void setIdmascota(Integer idmascota) {
        this.idmascota = idmascota;
    }
    public Integer getIddoctor() {
        return this.iddoctor;
    }
    
    public void setIddoctor(Integer iddoctor) {
        this.iddoctor = iddoctor;
    }
    public Date getFechaCita() {
        return this.fechaCita;
    }
    
    public void setFechaCita(Date fechaCita) {
        this.fechaCita = fechaCita;
    }




}


