package pe.com.soappet.dominio;
// Generated 11/06/2015 12:21:32 AM by Hibernate Tools 4.3.1



/**
 * Mascota generated by hbm2java
 */
public class Mascota  implements java.io.Serializable {


     private Integer idMascota;
     private String nombre;
     private String apellido;
     private String raza;
     private Integer edad;
     private Double peso;
     private Integer idcliente;
     private Integer estado;

    public Mascota() {
    }

    public Mascota(String nombre, String apellido, String raza, Integer edad, Double peso, Integer idcliente) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.raza = raza;
       this.edad = edad;
       this.peso = peso;
       this.idcliente = idcliente;
    }
   
    public Integer getIdMascota() {
        return this.idMascota;
    }
    
    public void setIdMascota(Integer idMascota) {
        this.idMascota = idMascota;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getRaza() {
        return this.raza;
    }
    
    public void setRaza(String raza) {
        this.raza = raza;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public Double getPeso() {
        return this.peso;
    }
    
    public void setPeso(Double peso) {
        this.peso = peso;
    }
    public Integer getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(Integer idcliente) {
        this.idcliente = idcliente;
    }

    /**
     * @return the estado
     */
    public Integer getEstado() {
        return estado;
    }

    /**
     * @param estado the estado to set
     */
    public void setEstado(Integer estado) {
        this.estado = estado;
    }




}


